# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_updated.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(546, 436)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("BootIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"\n"
"tabWidget {border: 2px solid rgb(255, 146, 73);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.proButton = QtWidgets.QPushButton(self.centralwidget)
        self.proButton.setGeometry(QtCore.QRect(30, 55, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.proButton.setFont(font)
        self.proButton.setMouseTracking(False)
        self.proButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(29, 29, 29);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 128, 43);\n"
"border-radius: 8px;}\n"
"\n"
"QPushButton:hover {background: rgb(85, 85, 85);}")
        self.proButton.setObjectName("proButton")
        self.appButton = QtWidgets.QPushButton(self.centralwidget)
        self.appButton.setGeometry(QtCore.QRect(30, 145, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.appButton.setFont(font)
        self.appButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(29, 29, 29);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 128, 43);\n"
"border-radius: 8px;}\n"
"\n"
"QPushButton:hover {background: rgb(85, 85, 85);}")
        self.appButton.setObjectName("appButton")
        self.launchButton = QtWidgets.QPushButton(self.centralwidget)
        self.launchButton.setGeometry(QtCore.QRect(30, 328, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.launchButton.setFont(font)
        self.launchButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(29, 29, 29);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 128, 43);\n"
"border-radius: 8px;}\n"
"\n"
"QPushButton:hover {background: rgb(85, 85, 85);}")
        self.launchButton.setObjectName("launchButton")
        self.proNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.proNameEdit.setGeometry(QtCore.QRect(30, 105, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.proNameEdit.setFont(font)
        self.proNameEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"padding-left: 5px")
        self.proNameEdit.setText("")
        self.proNameEdit.setObjectName("proNameEdit")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(179, 24, 341, 371))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("QWidget {background: 2px solid rgb(255, 128, 43);}\n"
"\n"
"QListWidget {\n"
"    border: 5px solid rgb(68, 68, 68);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        #self.tabWidget.setIconSize(QtCore.QSize(44, 30))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        #self.tab = QtWidgets.QWidget()
        #self.tab.setEnabled(True)
        #self.tab.setStyleSheet("background: 2px solid rgb(255, 128, 43);")
        #self.tab.setObjectName("tab")
        #self.tab1_listWidget = QtWidgets.QListWidget(self.tab)
        #self.tab1_listWidget.setGeometry(QtCore.QRect(12, 15, 310, 310))
        #font = QtGui.QFont()
        #font.setPointSize(10)
        #self.tab1_listWidget.setFont(font)
        #self.tab1_listWidget.setStyleSheet("\n"
#"background-color: rgb(255, 255, 255);")
        #self.tab1_listWidget.setObjectName("tab1_listWidget")
        #item = QtWidgets.QListWidgetItem()
        #self.tab1_listWidget.addItem(item)
        #item = QtWidgets.QListWidgetItem()
        #self.tab1_listWidget.addItem(item)
        #self.tabWidget.addTab(self.tab, "")
        #self.tab_2 = QtWidgets.QWidget()
        #self.tab_2.setEnabled(True)
        #self.tab_2.setStyleSheet("")
        #self.tab_2.setObjectName("tab_2")
        #self.tab1_listWidget_2 = QtWidgets.QListWidget(self.tab_2)
        #self.tab1_listWidget_2.setGeometry(QtCore.QRect(10, 10, 311, 311))
        #self.tab1_listWidget_2.setStyleSheet("")
        #self.tab1_listWidget_2.setObjectName("tab1_listWidget_2")
        #self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 546, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BootTool v1.0"))
        self.proButton.setText(_translate("MainWindow", "Add Profile"))
        self.appButton.setText(_translate("MainWindow", "Add App"))
        self.launchButton.setText(_translate("MainWindow", "Launch"))
        self.proNameEdit.setPlaceholderText(_translate("MainWindow", "Name"))
        #__sortingEnabled = self.tab1_listWidget.isSortingEnabled()
        #self.tab1_listWidget.setSortingEnabled(False)
        #item = self.tab1_listWidget.item(0)
        #item.setText(_translate("MainWindow", "Test"))
        #item = self.tab1_listWidget.item(1)
        #item.setText(_translate("MainWindow", "Other Test"))
        #self.tab1_listWidget.setSortingEnabled(__sortingEnabled)
        #self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        #self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
